defmodule Orangerie.Repo.Migrations.EventSeries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:event_series) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end
  end

  def down do
    alter table(:event_series) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end
  end
end
