defmodule Orangerie.Repo.Migrations.ExtendUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :username, :text, null: false
      add :slug, :citext, null: false
      add :type, :text
    end

    create unique_index(:users, [:slug], name: "users_unique_slug_index")

    create unique_index(:users, [:username], name: "users_unique_username_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:username], name: "users_unique_username_index")

    drop_if_exists unique_index(:users, [:slug], name: "users_unique_slug_index")

    alter table(:users) do
      remove :type
      remove :slug
      remove :username
    end
  end
end
