defmodule Orangerie.Repo.Migrations.FinalizeEventSeries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :date, :date, null: false
      add :start_time, :time, null: false
      add :title, :map, null: false
      add :description, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_series_id, :uuid, null: false
    end

    create table(:event_series, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:events) do
      modify :event_series_id,
             references(:event_series,
               column: :id,
               name: "events_event_series_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:event_series) do
      add :slug, :text, null: false
      add :name, :map, null: false
      add :allowed_profile_types, {:array, :text}, null: false
    end

    create unique_index(:event_series, [:slug], name: "event_series_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:event_series, [:slug], name: "event_series_unique_slug_index")

    alter table(:event_series) do
      remove :allowed_profile_types
      remove :name
      remove :slug
    end

    drop constraint(:events, "events_event_series_id_fkey")

    alter table(:events) do
      modify :event_series_id, :uuid
    end

    drop table(:event_series)

    drop table(:events)
  end
end
