defmodule Orangerie.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :slug, :citext, null: false
    end

    create unique_index(:users, [:slug], name: "users_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:slug], name: "users_unique_slug_index")

    alter table(:users) do
      remove :slug
    end
  end
end
