defmodule Orangerie.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:event_series) do
      add :allowed_profile_types, {:array, :text}, null: false
    end
  end

  def down do
    alter table(:event_series) do
      remove :allowed_profile_types
    end
  end
end
