defmodule Orangerie.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:event_series) do
      add :name, :map, null: false
    end
  end

  def down do
    alter table(:event_series) do
      remove :name
    end
  end
end
