defmodule Orangerie.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:event_series, primary_key: false) do
      add :slug, :text, null: false, primary_key: true
    end
  end

  def down do
    drop table(:event_series)
  end
end
